version: {branch}-{build}
clone_folder: c:\project

environment:
  matrix:
    - PYTHON: "c:\\python35-x64"
    - PYTHON: "c:\\python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r c:\\project\\dev.requirements.txt"

build:
  - "%PYTHON%\\python.exe setup.py sdist"

test_script:
  - "%PYTHON%\\python.exe -m nosetests --verbose"

artifacts:
  - path: dist\*
