version: 1.0.{build}
clone_folder: c:\project

skip_commits:
  message: /travis/

environment:
  matrix:
    - PYTHON: "c:\\python35-x64"
    - PYTHON: "c:\\python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r c:\\project\\dev.requirements.txt"

build_script:
  - "%PYTHON%\\python.exe setup.py sdist"

test_script:
  - "%PYTHON%\\python.exe -m nose --verbose"

artifacts:
  - path: dist\*
