language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  pip install -r dev.requirements.txt
  pip install coveralls
script:
  - nosetests --cover-branches --with-coverage --cover-erase --verbose --cover-package=exceptive
after_success: coveralls
