language: python
python: "3.7"
jobs:
  include:
    - stage: "Testing with Specified requests"
      python:
        - "3.5"
        - "3.6"
        - "3.7"
      install: pip install -r dev.requirements.txt
      script:
        - nosetests --verbose
    - stage: "Testing with Latest Stable requests"
      python:
        - "3.5"
        - "3.6"
        - "3.7"
      install:
        - pip install -r dev.requirements.txt
        - pip install requests
      script:
        - nosetests --verbose
name: "Covering Package"
install:
  - pip install -r dev.requirements.txt
  - pip install coverage coveralls
script:
  - nosetests --cover-branches --with-coverage --cover-erase --verbose --cover-package=pyairmore
after_success: coveralls
