site_name: PyAirmore
site_author: Eray Erdin
repo_url: https://github.com/erayerdin/pyairmore
theme: readthedocs
google_analytics: ['UA-128604085-1', 'pyairmore.readthedocs.io']
nav:
  - index.md
  - Requesting and Session:
      - requesting-and-session/index.md
      - requesting-and-session/custom-requests.md
      - requesting-and-session/how-session-works.md
  - Services:
      - services/index.md
      - services/device-service.md
      - services/messaging-service.md
