site_name: PyAirmore
site_author: Eray Erdin
repo_url: https://github.com/erayerdin/pyairmore
theme: readthedocs
nav:
  - index.md
  - Requesting and Session:
      - requesting-and-session/index.md
      - requesting-and-session/custom-requests.md
      - requesting-and-session/how-session-works.md
